### ISSUE TITLE
TypeError in json.dumps when using python3

### ISSUE THREAD

**Issue by rajasaur** [awslabs/aws-detailed-billing-parser#6]
There is a 
TypeError: __init__() got an unexpected keyword argument 'encoding'
when running this against Python3 as json.dumps doesnt support the encoding option anymore. Its expected that the data be converted before passing into the dumps method. (https://docs.python.org/3/library/json.html#json.dumps)

**Comment by koiker** [comment]
Thanks for finding this.
Encoding is something that is really hard to design correctly between Python 2.X and 3.X as in Python 2 we default to ascii while Python 3 default to utf-8
I will review this and apply the corrections!

**Comment by koiker** [comment]
I have started testing the dbrparser with Python 3 but in my case it's working correctly.
Can you share the steps that you executed to get the error?
My Python3 is 3.5.2, what version your are running?

**Comment by rajasaur** [comment]
@koiker , we were also using the same python. Can you try the "config.process_mode == PROCESS_BY_LINE" mode(https://github.com/awslabs/aws-detailed-billing-parser/blob/master/awsdbrparser/parser.py#L288)  as thats the one that has the encoding argument in json.dumps. Ill get more details from my team and update.

**Comment by koiker** [comment]
Solved the problem in version 0.5.2
Removed the encoding parameter as this parameter has been deprecated by json library in Python 3
