### ISSUE TITLE
JSON Array vs JSON Objects

### ISSUE THREAD

**Issue by jujinfu** [awslabs/aws-detailed-billing-parser#7]
Maybe I am doing this wrong. But the result files is stored as many objects and they are not in an array.

This will cause some other program only recognize first row. I had to manually change the file into an array of objects.

Please let me know

**Comment by koiker** [comment]
I've written the output to file to write row by row json objects because you can easily ingest those rows in ElasticSearch.
But it's not hard to include a parameter to build a single json object with an array of rows. Which tools you need to use that receive a single json object?

**Comment by jujinfu** [comment]
I am trying to parse them then import them into Database for SSAS.

I’ve already changed a little bit to make it generate it as one single JSON object. But it was not an elegant way doing it.

Also I notice sometimes it’s not getting rid of the summary rows.



Sent from my iPhone

On Sep 27, 2017, at 04:25, Rafael M. Koike <notifications@github.com<mailto:notifications@github.com>> wrote:


I've written the output to file to write row by row json objects because you can easily ingest those rows in ElasticSearch.
But it's not hard to include a parameter to build a single json object with an array of rows. Which tools you need to use that receive a single json object?

**Comment by koiker** [comment]
I'm closing this issue and add the suggestion in the roadmap.
