### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by zhangsj** [awslabs/aws-detailed-billing-parser#8]
Installed /home/prod/softwares/python/lib/python2.7/site-packages/awsdbrparser-0.5.4-py2.7.egg
Processing dependencies for awsdbrparser==0.5.4
Searching for requests-aws4auth>=0.9.0
Reading http://pypi.python.org/simple/requests-aws4auth/
Couldn't find index page for 'requests-aws4auth' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading http://pypi.python.org/simple/
No local packages or download links found for requests-aws4auth>=0.9.0
Best match: None
Traceback (most recent call last):
  File "setup.py", line 86, in <module>
    'Topic :: Utilities',

**Comment by zhangsj** [comment]
#pip list
awsdbrparser (0.5.4)
boto3 (1.4.7)
botocore (1.7.39)
docutils (0.14)
elasticsearch (1.6.0)
futures (3.1.1)
jmespath (0.9.3)
MySQL-python (1.2.3)
pip (1.5.6)
python-dateutil (2.6.1)
requests (2.7.0)
requests-aws4auth (0.9)
s3transfer (0.1.11)
setuptools (0.6c11)
simplejson (3.8.0)
six (1.11.0)
urllib3 (1.11)
wsgiref (0.1.2)

**Comment by koiker** [comment]
Strange, the build is passing and the package exists.
Maybe was a pypi bug?
Did you tried to install again later?
